FROM openjdk:8-jdk-alpine
VOLUME /tmp
RUN chmod +x /tmp
COPY /target/portal-quarkus-0.0.1-SNAPSHOT-runner.jar /app.jar
EXPOSE 8080
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]